name: .NET

on:
  push:
    branches: '*'
    tags: '*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack -c Release -p:Version=${GITHUB_REF#refs/*/} -o out
      if: startsWith(github.ref, 'refs/tags/')
    - name: Push
      run: dotnet nuget push out/**/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
      if: startsWith(github.ref, 'refs/tags/')
      
